# Elo ratings updated from Warren Nolan

SEC_TEAMS = [{'name': 'Georgia', 'group_id': 'A', 'elo': 1775.8},
 {'name': 'Florida', 'group_id': 'A', 'elo': 1504.3},
 {'name': 'South Carolina', 'group_id': 'A', 'elo': 1525.2},
 {'name': 'Kentucky', 'group_id': 'A', 'elo': 1490.7},
 {'name': 'Alabama', 'group_id': 'B', 'elo': 1726.8},
 {'name': 'Auburn', 'group_id': 'B', 'elo': 1547.7},
 {'name': 'Tennessee', 'group_id': 'B', 'elo': 1655.8},
 {'name': 'Vanderbilt', 'group_id': 'B', 'elo': 1645.8},
 {'name': 'LSU', 'group_id': 'C', 'elo': 1644.8},
 {'name': 'Ole Miss', 'group_id': 'C', 'elo': 1752.3},
 {'name': 'Miss State', 'group_id': 'C', 'elo': 1454.7},
 {'name': 'Arkansas', 'group_id': 'C', 'elo': 1409.1},
 {'name': 'Texas', 'group_id': 'D', 'elo': 1706.8},
 {'name': 'Texas A&M', 'group_id': 'D', 'elo': 1742.7},
 {'name': 'Oklahoma', 'group_id': 'D', 'elo': 1727.3},
 {'name': 'Missouri', 'group_id': 'D', 'elo': 1604.6}]

BIG_XII_TEAMS = [{'name': 'Utah', 'group_id': 'A', 'elo': 1701.7},
 {'name': 'BYU', 'group_id': 'A', 'elo': 1708.6},
 {'name': 'Arizona', 'group_id': 'A', 'elo': 1621.2},
 {'name': 'Arizona State', 'group_id': 'A', 'elo': 1627.4},
 {'name': 'Kansas State', 'group_id': 'B', 'elo': 1560.6},
 {'name': 'Kansas', 'group_id': 'B', 'elo': 1475.5},
 {'name': 'Iowa State', 'group_id': 'B', 'elo': 1608.7},
 {'name': 'Colorado', 'group_id': 'B', 'elo': 1431.9},
 {'name': 'Oklahoma State', 'group_id': 'C', 'elo': 1302.6},
 {'name': 'TCU', 'group_id': 'C', 'elo': 1588.6},
 {'name': 'Texas Tech', 'group_id': 'C', 'elo': 1717.1},
 {'name': 'Baylor', 'group_id': 'C', 'elo': 1467.7},
 {'name': 'West Virginia', 'group_id': 'D', 'elo': 1449.6},
 {'name': 'UCF', 'group_id': 'D', 'elo': 1447.9},
 {'name': 'Cincinnati', 'group_id': 'D', 'elo': 1533.9},
 {'name': 'Houston', 'group_id': 'D', 'elo': 1567.6}]
